// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SuperUser.proto

package com.ibiz.redis.mq.domain;

public final class SuperUserProto {
  private SuperUserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SuperUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ibiz.redis.mq.domain.SuperUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 level = 1;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 1;</code>
     */
    int getLevel();

    /**
     * <code>optional bool admin = 2;</code>
     */
    boolean hasAdmin();
    /**
     * <code>optional bool admin = 2;</code>
     */
    boolean getAdmin();

    /**
     * <code>repeated string list = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getListList();
    /**
     * <code>repeated string list = 3;</code>
     */
    int getListCount();
    /**
     * <code>repeated string list = 3;</code>
     */
    java.lang.String getList(int index);
    /**
     * <code>repeated string list = 3;</code>
     */
    com.google.protobuf.ByteString
        getListBytes(int index);
  }
  /**
   * Protobuf type {@code com.ibiz.redis.mq.domain.SuperUser}
   */
  public static final class SuperUser extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ibiz.redis.mq.domain.SuperUser)
      SuperUserOrBuilder {
    // Use SuperUser.newBuilder() to construct.
    private SuperUser(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SuperUser(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SuperUser defaultInstance;
    public static SuperUser getDefaultInstance() {
      return defaultInstance;
    }

    public SuperUser getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SuperUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              level_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              admin_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                list_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              list_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = list_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ibiz.redis.mq.domain.SuperUserProto.internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ibiz.redis.mq.domain.SuperUserProto.internal_static_com_ibiz_redis_mq_domain_SuperUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.class, com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder.class);
    }

    public static com.google.protobuf.Parser<SuperUser> PARSER =
        new com.google.protobuf.AbstractParser<SuperUser>() {
      public SuperUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuperUser(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SuperUser> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>optional int32 level = 1;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int ADMIN_FIELD_NUMBER = 2;
    private boolean admin_;
    /**
     * <code>optional bool admin = 2;</code>
     */
    public boolean hasAdmin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool admin = 2;</code>
     */
    public boolean getAdmin() {
      return admin_;
    }

    public static final int LIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList list_;
    /**
     * <code>repeated string list = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_;
    }
    /**
     * <code>repeated string list = 3;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 3;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 3;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }

    private void initFields() {
      level_ = 0;
      admin_ = false;
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, admin_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(3, list_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, admin_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ibiz.redis.mq.domain.SuperUserProto.SuperUser prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ibiz.redis.mq.domain.SuperUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ibiz.redis.mq.domain.SuperUser)
        com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ibiz.redis.mq.domain.SuperUserProto.internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ibiz.redis.mq.domain.SuperUserProto.internal_static_com_ibiz_redis_mq_domain_SuperUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.class, com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder.class);
      }

      // Construct using com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        admin_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ibiz.redis.mq.domain.SuperUserProto.internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor;
      }

      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser getDefaultInstanceForType() {
        return com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance();
      }

      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser build() {
        com.ibiz.redis.mq.domain.SuperUserProto.SuperUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser buildPartial() {
        com.ibiz.redis.mq.domain.SuperUserProto.SuperUser result = new com.ibiz.redis.mq.domain.SuperUserProto.SuperUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.admin_ = admin_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = list_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.list_ = list_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ibiz.redis.mq.domain.SuperUserProto.SuperUser) {
          return mergeFrom((com.ibiz.redis.mq.domain.SuperUserProto.SuperUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ibiz.redis.mq.domain.SuperUserProto.SuperUser other) {
        if (other == com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance()) return this;
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasAdmin()) {
          setAdmin(other.getAdmin());
        }
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ibiz.redis.mq.domain.SuperUserProto.SuperUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ibiz.redis.mq.domain.SuperUserProto.SuperUser) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int level_ ;
      /**
       * <code>optional int32 level = 1;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000001;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 1;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        onChanged();
        return this;
      }

      private boolean admin_ ;
      /**
       * <code>optional bool admin = 2;</code>
       */
      public boolean hasAdmin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool admin = 2;</code>
       */
      public boolean getAdmin() {
        return admin_;
      }
      /**
       * <code>optional bool admin = 2;</code>
       */
      public Builder setAdmin(boolean value) {
        bitField0_ |= 0x00000002;
        admin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool admin = 2;</code>
       */
      public Builder clearAdmin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        admin_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          list_ = new com.google.protobuf.LazyStringArrayList(list_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getListList() {
        return list_.getUnmodifiableView();
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public java.lang.String getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public com.google.protobuf.ByteString
          getListBytes(int index) {
        return list_.getByteString(index);
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public Builder setList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public Builder addList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<java.lang.String> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public Builder clearList() {
        list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string list = 3;</code>
       */
      public Builder addListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ibiz.redis.mq.domain.SuperUser)
    }

    static {
      defaultInstance = new SuperUser(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ibiz.redis.mq.domain.SuperUser)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ibiz_redis_mq_domain_SuperUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SuperUser.proto\022\030com.ibiz.redis.mq.dom" +
      "ain\"7\n\tSuperUser\022\r\n\005level\030\001 \001(\005\022\r\n\005admin" +
      "\030\002 \001(\010\022\014\n\004list\030\003 \003(\tB*\n\030com.ibiz.redis.m" +
      "q.domainB\016SuperUserProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ibiz_redis_mq_domain_SuperUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ibiz_redis_mq_domain_SuperUser_descriptor,
        new java.lang.String[] { "Level", "Admin", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
