// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.ibiz.redis.mq.domain;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ibiz.redis.mq.domain.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 age = 1;</code>
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 1;</code>
     */
    int getAge();

    /**
     * <code>optional double price = 2;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional double price = 2;</code>
     */
    double getPrice();

    /**
     * <code>optional float amount = 3;</code>
     */
    boolean hasAmount();
    /**
     * <code>optional float amount = 3;</code>
     */
    float getAmount();

    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> 
        getMapList();
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    com.ibiz.redis.mq.domain.DefineMapProto.DefineMap getMap(int index);
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    int getMapCount();
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    java.util.List<? extends com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder> 
        getMapOrBuilderList();
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder getMapOrBuilder(
        int index);

    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    boolean hasSuperUser();
    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    com.ibiz.redis.mq.domain.SuperUserProto.SuperUser getSuperUser();
    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder getSuperUserOrBuilder();

    /**
     * <code>optional string name = 6;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.ibiz.redis.mq.domain.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ibiz.redis.mq.domain.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              age_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              price_ = input.readDouble();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              amount_ = input.readFloat();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                map_ = new java.util.ArrayList<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap>();
                mutable_bitField0_ |= 0x00000008;
              }
              map_.add(input.readMessage(com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = superUser_.toBuilder();
              }
              superUser_ = input.readMessage(com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(superUser_);
                superUser_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          map_ = java.util.Collections.unmodifiableList(map_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ibiz.redis.mq.domain.UserProto.internal_static_com_ibiz_redis_mq_domain_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ibiz.redis.mq.domain.UserProto.internal_static_com_ibiz_redis_mq_domain_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ibiz.redis.mq.domain.UserProto.User.class, com.ibiz.redis.mq.domain.UserProto.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <code>optional int32 age = 1;</code>
     */
    public boolean hasAge() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 age = 1;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_;
    /**
     * <code>optional double price = 2;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double price = 2;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private float amount_;
    /**
     * <code>optional float amount = 3;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float amount = 3;</code>
     */
    public float getAmount() {
      return amount_;
    }

    public static final int MAP_FIELD_NUMBER = 4;
    private java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> map_;
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    public java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> getMapList() {
      return map_;
    }
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    public java.util.List<? extends com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder> 
        getMapOrBuilderList() {
      return map_;
    }
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    public int getMapCount() {
      return map_.size();
    }
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    public com.ibiz.redis.mq.domain.DefineMapProto.DefineMap getMap(int index) {
      return map_.get(index);
    }
    /**
     * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
     */
    public com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder getMapOrBuilder(
        int index) {
      return map_.get(index);
    }

    public static final int SUPERUSER_FIELD_NUMBER = 5;
    private com.ibiz.redis.mq.domain.SuperUserProto.SuperUser superUser_;
    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    public boolean hasSuperUser() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser getSuperUser() {
      return superUser_;
    }
    /**
     * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
     */
    public com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder getSuperUserOrBuilder() {
      return superUser_;
    }

    public static final int NAME_FIELD_NUMBER = 6;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 6;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      age_ = 0;
      price_ = 0D;
      amount_ = 0F;
      map_ = java.util.Collections.emptyList();
      superUser_ = com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance();
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, age_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, amount_);
      }
      for (int i = 0; i < map_.size(); i++) {
        output.writeMessage(4, map_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, superUser_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, amount_);
      }
      for (int i = 0; i < map_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, map_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, superUser_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ibiz.redis.mq.domain.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ibiz.redis.mq.domain.UserProto.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ibiz.redis.mq.domain.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ibiz.redis.mq.domain.User)
        com.ibiz.redis.mq.domain.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ibiz.redis.mq.domain.UserProto.internal_static_com_ibiz_redis_mq_domain_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ibiz.redis.mq.domain.UserProto.internal_static_com_ibiz_redis_mq_domain_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ibiz.redis.mq.domain.UserProto.User.class, com.ibiz.redis.mq.domain.UserProto.User.Builder.class);
      }

      // Construct using com.ibiz.redis.mq.domain.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMapFieldBuilder();
          getSuperUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          mapBuilder_.clear();
        }
        if (superUserBuilder_ == null) {
          superUser_ = com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance();
        } else {
          superUserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ibiz.redis.mq.domain.UserProto.internal_static_com_ibiz_redis_mq_domain_User_descriptor;
      }

      public com.ibiz.redis.mq.domain.UserProto.User getDefaultInstanceForType() {
        return com.ibiz.redis.mq.domain.UserProto.User.getDefaultInstance();
      }

      public com.ibiz.redis.mq.domain.UserProto.User build() {
        com.ibiz.redis.mq.domain.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ibiz.redis.mq.domain.UserProto.User buildPartial() {
        com.ibiz.redis.mq.domain.UserProto.User result = new com.ibiz.redis.mq.domain.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.age_ = age_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.amount_ = amount_;
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            map_ = java.util.Collections.unmodifiableList(map_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.map_ = map_;
        } else {
          result.map_ = mapBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (superUserBuilder_ == null) {
          result.superUser_ = superUser_;
        } else {
          result.superUser_ = superUserBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ibiz.redis.mq.domain.UserProto.User) {
          return mergeFrom((com.ibiz.redis.mq.domain.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ibiz.redis.mq.domain.UserProto.User other) {
        if (other == com.ibiz.redis.mq.domain.UserProto.User.getDefaultInstance()) return this;
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (mapBuilder_ == null) {
          if (!other.map_.isEmpty()) {
            if (map_.isEmpty()) {
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureMapIsMutable();
              map_.addAll(other.map_);
            }
            onChanged();
          }
        } else {
          if (!other.map_.isEmpty()) {
            if (mapBuilder_.isEmpty()) {
              mapBuilder_.dispose();
              mapBuilder_ = null;
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000008);
              mapBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMapFieldBuilder() : null;
            } else {
              mapBuilder_.addAllMessages(other.map_);
            }
          }
        }
        if (other.hasSuperUser()) {
          mergeSuperUser(other.getSuperUser());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000020;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ibiz.redis.mq.domain.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ibiz.redis.mq.domain.UserProto.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int age_ ;
      /**
       * <code>optional int32 age = 1;</code>
       */
      public boolean hasAge() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 age = 1;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 1;</code>
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000001;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 1;</code>
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 2;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double price = 2;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 2;</code>
       */
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 2;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        onChanged();
        return this;
      }

      private float amount_ ;
      /**
       * <code>optional float amount = 3;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float amount = 3;</code>
       */
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>optional float amount = 3;</code>
       */
      public Builder setAmount(float value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float amount = 3;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> map_ =
        java.util.Collections.emptyList();
      private void ensureMapIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          map_ = new java.util.ArrayList<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap>(map_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ibiz.redis.mq.domain.DefineMapProto.DefineMap, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder, com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder> mapBuilder_;

      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> getMapList() {
        if (mapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(map_);
        } else {
          return mapBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public int getMapCount() {
        if (mapBuilder_ == null) {
          return map_.size();
        } else {
          return mapBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public com.ibiz.redis.mq.domain.DefineMapProto.DefineMap getMap(int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);
        } else {
          return mapBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder setMap(
          int index, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.set(index, value);
          onChanged();
        } else {
          mapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder setMap(
          int index, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder addMap(com.ibiz.redis.mq.domain.DefineMapProto.DefineMap value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(value);
          onChanged();
        } else {
          mapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder addMap(
          int index, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(index, value);
          onChanged();
        } else {
          mapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder addMap(
          com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder addMap(
          int index, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder addAllMap(
          java.lang.Iterable<? extends com.ibiz.redis.mq.domain.DefineMapProto.DefineMap> values) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, map_);
          onChanged();
        } else {
          mapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder clearMap() {
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          mapBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public Builder removeMap(int index) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.remove(index);
          onChanged();
        } else {
          mapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder getMapBuilder(
          int index) {
        return getMapFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder getMapOrBuilder(
          int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);  } else {
          return mapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public java.util.List<? extends com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder> 
           getMapOrBuilderList() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(map_);
        }
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder addMapBuilder() {
        return getMapFieldBuilder().addBuilder(
            com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder addMapBuilder(
          int index) {
        return getMapFieldBuilder().addBuilder(
            index, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ibiz.redis.mq.domain.DefineMap map = 4;</code>
       */
      public java.util.List<com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder> 
           getMapBuilderList() {
        return getMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ibiz.redis.mq.domain.DefineMapProto.DefineMap, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder, com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ibiz.redis.mq.domain.DefineMapProto.DefineMap, com.ibiz.redis.mq.domain.DefineMapProto.DefineMap.Builder, com.ibiz.redis.mq.domain.DefineMapProto.DefineMapOrBuilder>(
                  map_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }

      private com.ibiz.redis.mq.domain.SuperUserProto.SuperUser superUser_ = com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.ibiz.redis.mq.domain.SuperUserProto.SuperUser, com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder, com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder> superUserBuilder_;
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public boolean hasSuperUser() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser getSuperUser() {
        if (superUserBuilder_ == null) {
          return superUser_;
        } else {
          return superUserBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public Builder setSuperUser(com.ibiz.redis.mq.domain.SuperUserProto.SuperUser value) {
        if (superUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          superUser_ = value;
          onChanged();
        } else {
          superUserBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public Builder setSuperUser(
          com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder builderForValue) {
        if (superUserBuilder_ == null) {
          superUser_ = builderForValue.build();
          onChanged();
        } else {
          superUserBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public Builder mergeSuperUser(com.ibiz.redis.mq.domain.SuperUserProto.SuperUser value) {
        if (superUserBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              superUser_ != com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance()) {
            superUser_ =
              com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.newBuilder(superUser_).mergeFrom(value).buildPartial();
          } else {
            superUser_ = value;
          }
          onChanged();
        } else {
          superUserBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public Builder clearSuperUser() {
        if (superUserBuilder_ == null) {
          superUser_ = com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.getDefaultInstance();
          onChanged();
        } else {
          superUserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder getSuperUserBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSuperUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      public com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder getSuperUserOrBuilder() {
        if (superUserBuilder_ != null) {
          return superUserBuilder_.getMessageOrBuilder();
        } else {
          return superUser_;
        }
      }
      /**
       * <code>optional .com.ibiz.redis.mq.domain.SuperUser superUser = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ibiz.redis.mq.domain.SuperUserProto.SuperUser, com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder, com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder> 
          getSuperUserFieldBuilder() {
        if (superUserBuilder_ == null) {
          superUserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ibiz.redis.mq.domain.SuperUserProto.SuperUser, com.ibiz.redis.mq.domain.SuperUserProto.SuperUser.Builder, com.ibiz.redis.mq.domain.SuperUserProto.SuperUserOrBuilder>(
                  getSuperUser(),
                  getParentForChildren(),
                  isClean());
          superUser_ = null;
        }
        return superUserBuilder_;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 6;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ibiz.redis.mq.domain.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ibiz.redis.mq.domain.User)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ibiz_redis_mq_domain_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ibiz_redis_mq_domain_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\030com.ibiz.redis.mq.domain\032\017" +
      "DefineMap.proto\032\017SuperUser.proto\"\252\001\n\004Use" +
      "r\022\013\n\003age\030\001 \001(\005\022\r\n\005price\030\002 \001(\001\022\016\n\006amount\030" +
      "\003 \001(\002\0220\n\003map\030\004 \003(\0132#.com.ibiz.redis.mq.d" +
      "omain.DefineMap\0226\n\tsuperUser\030\005 \001(\0132#.com" +
      ".ibiz.redis.mq.domain.SuperUser\022\014\n\004name\030" +
      "\006 \001(\tB%\n\030com.ibiz.redis.mq.domainB\tUserP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ibiz.redis.mq.domain.DefineMapProto.getDescriptor(),
          com.ibiz.redis.mq.domain.SuperUserProto.getDescriptor(),
        }, assigner);
    internal_static_com_ibiz_redis_mq_domain_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ibiz_redis_mq_domain_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ibiz_redis_mq_domain_User_descriptor,
        new java.lang.String[] { "Age", "Price", "Amount", "Map", "SuperUser", "Name", });
    com.ibiz.redis.mq.domain.DefineMapProto.getDescriptor();
    com.ibiz.redis.mq.domain.SuperUserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
